# Generated by Django 2.2 on 2023-05-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproject',
            old_name='description',
            new_name='descr_one',
        ),
    ]
